# Generated by Django 3.2.3 on 2021-05-25 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Preço')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Foto')),
                ('resutaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Prato',
                'verbose_name_plural': 'Pratos',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('MN', 'Dinheiro'), ('DC', 'Cartão de Débito'), ('CC', 'Cartão de Crédito')], max_length=2, verbose_name='Forma de Pagamento')),
                ('quantity', models.PositiveBigIntegerField(verbose_name='Quantidade')),
                ('total', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Total do Pedido')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.dish', verbose_name='Prato')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant', verbose_name='Restaurante')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
